//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан вручную, чтобы надёжно работать на CI без VS-Designer.
//------------------------------------------------------------------------------
using System.Drawing;
using System.Windows.Forms;

namespace TrayPassGen
{
    partial class SettingsForm
    {
        private NumericUpDown nudLength;
        private TextBox tbPrefix;
        private CheckBox cbLower;
        private CheckBox cbUpper;
        private CheckBox cbDigits;
        private CheckBox cbSpecial;
        private CheckBox cbSafeSymbols;
        private Button btnSave;
        private Label labelLength;
        private Label labelPrefix;

        /// <summary>Необходимый метод для поддержки конструктора.</summary>
        private void InitializeComponent()
        {
            nudLength      = new NumericUpDown();
            tbPrefix       = new TextBox();
            cbLower        = new CheckBox();
            cbUpper        = new CheckBox();
            cbDigits       = new CheckBox();
            cbSpecial      = new CheckBox();
            cbSafeSymbols  = new CheckBox();
            btnSave        = new Button();
            labelLength    = new Label();
            labelPrefix    = new Label();
            ((System.ComponentModel.ISupportInitialize)(nudLength)).BeginInit();
            SuspendLayout();

            // ───── Чекбоксы ────────────────────────────────────────────────
            cbLower.Text     = "Строчные буквы (a-z)";
            cbLower.Location = new Point(12, 12);
            cbLower.AutoSize = true;

            cbUpper.Text     = "Заглавные буквы (A-Z)";
            cbUpper.Location = new Point(12, 35);
            cbUpper.AutoSize = true;

            cbDigits.Text     = "Цифры (0-9)";
            cbDigits.Location = new Point(12, 58);
            cbDigits.AutoSize = true;

            cbSpecial.Text     = "Спецсимволы (!@#$)";
            cbSpecial.Location = new Point(12, 81);
            cbSpecial.AutoSize = true;

            cbSafeSymbols.Text     = "Только безопасные спецсимволы (_-+=!@#.)";
            cbSafeSymbols.Location = new Point(12, 104);
            cbSafeSymbols.AutoSize = true;

            // ───── Длина ───────────────────────────────────────────────────
            labelLength.Text     = "Длина пароля:";
            labelLength.Location = new Point(12, 137);
            labelLength.AutoSize = true;

            nudLength.Location = new Point(120, 135);
            nudLength.Minimum  = 4;
            nudLength.Maximum  = 128;
            nudLength.Value    = 16;                              // <— после Min/Max
            nudLength.Anchor   = AnchorStyles.Top | AnchorStyles.Left;
            nudLength.Validating += nudLength_Validating;

            // ───── Префикс ────────────────────────────────────────────────
            labelPrefix.Text     = "Префикс:";
            labelPrefix.Location = new Point(12, 167);
            labelPrefix.AutoSize = true;

            tbPrefix.Location = new Point(120, 164);
            tbPrefix.Size     = new Size(230, 23);
            tbPrefix.Anchor   = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;

            // ───── Кнопка Сохранить ───────────────────────────────────────
            btnSave.Text     = "Сохранить";
            btnSave.Size     = new Size(90, 30);
            btnSave.Location = new Point(275, 250);
            btnSave.Anchor   = AnchorStyles.Bottom | AnchorStyles.Right;
            btnSave.Click   += btnSave_Click;

            // ───── Форма ──────────────────────────────────────────────────
            AutoScaleMode = AutoScaleMode.Dpi;
            ClientSize    = new Size(500, 400);
            MinimumSize   = new Size(500, 400);
            Controls.AddRange(new Control[]
            {
                cbLower, cbUpper, cbDigits, cbSpecial, cbSafeSymbols,
                labelLength, nudLength, labelPrefix, tbPrefix, btnSave
            });
            Font            = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
            FormBorderStyle = FormBorderStyle.FixedDialog;
            MaximizeBox     = false;
            MinimizeBox     = false;
            StartPosition   = FormStartPosition.CenterScreen;
            Text            = "Настройки генератора";

            ((System.ComponentModel.ISupportInitialize)(nudLength)).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }
    }
}
