//------------------------------------------------------------------------------  
//  <auto-generated>                                                       
//     Ручной Resources.Designer.cs для CLI-сборки.                         
//------------------------------------------------------------------------------  
namespace TrayPassGen.Properties
{
    using System;
    using System.Drawing;
    using System.Resources;
    using System.Globalization;

    internal sealed class Resources
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;
        private static System.Globalization.CultureInfo resourceCulture;
        private Resources() { }

        private static ResourceManager ResourceManager =>
            resourceMan ??= new ResourceManager(
                "TrayPassGen.Properties.Resources",
                typeof(Resources).Assembly);

        /// <summary>Иконка PassGen (из Resources.resx)</summary>
        internal static Icon PassGen =>
            (Icon)ResourceManager.GetObject("PassGen", resourceCulture);
    }
}
