//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны
//     при повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrayPassGen.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGenerated()]
    [global::System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default => defaultInstance;

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("True")]
        public bool IncludeLowercase => ((bool)this["IncludeLowercase"]);

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("True")]
        public bool IncludeUppercase => ((bool)this["IncludeUppercase"]);

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("True")]
        public bool IncludeDigits => ((bool)this["IncludeDigits"]);

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("True")]
        public bool IncludeSpecialChars => ((bool)this["IncludeSpecialChars"]);

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("False")]
        public bool UseSafeSymbols => ((bool)this["UseSafeSymbols"]);

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("16")]
        public int PasswordLength => ((int)this["PasswordLength"]);

        [global::System.Configuration.UserScopedSetting()]
        [global::System.Diagnostics.DebuggerNonUserCode()]
        [global::System.Configuration.DefaultSettingValue("")]
        public string StaticPrefix => ((string)this["StaticPrefix"]);
    }
}
