//------------------------------------------------------------------------------
// <auto-generated>  Ручной Designer для CLI-сборки (.NET 8)
//------------------------------------------------------------------------------
namespace TrayPassGen.Properties
{
    using System.Configuration;
    using System.Diagnostics;

    [DebuggerNonUserCode]
    internal sealed partial class Settings : ApplicationSettingsBase
    {
        private static readonly Settings defaultInstance =
            (Settings)Synchronized(new Settings());

        public static Settings Default => defaultInstance;

        // 1. IncludeLowercase
        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("True")]
        public bool IncludeLowercase
        {
            get => (bool)this[nameof(IncludeLowercase)];
            set => this[nameof(IncludeLowercase)] = value;
        }

        // 2. IncludeUppercase
        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("True")]
        public bool IncludeUppercase
        {
            get => (bool)this[nameof(IncludeUppercase)];
            set => this[nameof(IncludeUppercase)] = value;
        }

        // 3. IncludeDigits
        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("True")]
        public bool IncludeDigits
        {
            get => (bool)this[nameof(IncludeDigits)];
            set => this[nameof(IncludeDigits)] = value;
        }

        // 4. IncludeSpecialChars
        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("True")]
        public bool IncludeSpecialChars
        {
            get => (bool)this[nameof(IncludeSpecialChars)];
            set => this[nameof(IncludeSpecialChars)] = value;
        }

        // 5. UseSafeSymbols
        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("False")]
        public bool UseSafeSymbols
        {
            get => (bool)this[nameof(UseSafeSymbols)];
            set => this[nameof(UseSafeSymbols)] = value;
        }

        // 6. PasswordLength
        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("16")]
        public int PasswordLength
        {
            get => (int)this[nameof(PasswordLength)];
            set => this[nameof(PasswordLength)] = value;
        }

        // 7. StaticPrefix
        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("")]
        public string StaticPrefix
        {
            get => (string)this[nameof(StaticPrefix)];
            set => this[nameof(StaticPrefix)] = value;
        }
    }
}
