//------------------------------------------------------------------------------
// <auto-generated>  (добавь при желании)
//------------------------------------------------------------------------------
namespace TrayPassGen.Properties
{
    internal sealed partial class Settings : System.Configuration.ApplicationSettingsBase
    {
        private static readonly Settings defaultInstance =
            (Settings)Synchronized(new Settings());

        public static Settings Default => defaultInstance;

        public bool IncludeLowercase
        {
            get => (bool)this["IncludeLowercase"];
            set => this["IncludeLowercase"] = value;
        }
        public bool IncludeUppercase
        {
            get => (bool)this["IncludeUppercase"];
            set => this["IncludeUppercase"] = value;
        }
        public bool IncludeDigits
        {
            get => (bool)this["IncludeDigits"];
            set => this["IncludeDigits"] = value;
        }
        public bool IncludeSpecialChars
        {
            get => (bool)this["IncludeSpecialChars"];
            set => this["IncludeSpecialChars"] = value;
        }
        public bool UseSafeSymbols
        {
            get => (bool)this["UseSafeSymbols"];
            set => this["UseSafeSymbols"] = value;
        }
        public int PasswordLength
        {
            get => (int)this["PasswordLength"];
            set => this["PasswordLength"] = value;
        }
        public string StaticPrefix
        {
            get => (string)this["StaticPrefix"];
            set => this["StaticPrefix"] = value;
        }
    }
}
