name: Build TrayPassGen

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. Клонируем репозиторий
    - name: Checkout
      uses: actions/checkout@v4

    # 2. Устанавливаем .NET SDK 8.x
    - name: Setup .NET 8.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # 3. Publish: self-contained + single-file + сжатие
    - name: Publish compact EXE
      shell: pwsh
      run: |
        dotnet publish TrayPassGen.csproj `
          -c Release `
          -r win-x64 `
          --self-contained true `
          /p:PublishSingleFile=true `
          /p:PublishReadyToRun=false `
          /p:IncludeNativeLibrariesForSelfExtract=false `
          /p:DebugType=None `
          /p:StripSymbols=true `
          /p:EnableCompressionInSingleFile=true `
          /p:InvariantGlobalization=true `
          --nologo

    # 4. Загружаем результат (один EXE)
    - name: Upload artefact
      uses: actions/upload-artifact@v4
      with:
        name: TrayPassGen
        path: |
          **/bin/Release/net8.0-windows/win-x64/publish/TrayPassGen.exe
